#!/usr/bin/env python3
"""
PM Snapshot JSON Export for PM Share Package

Exports pm.snapshot as JSON format by calling get_system_snapshot() directly.
This is the JSON version of the markdown snapshot generated by make pm.snapshot.

Usage:
    python scripts/util/export_pm_snapshot_json.py [--output <path>]
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

# Add project root to path
REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO))

OUT_DIR = REPO / "share"
OUT_FILE = OUT_DIR / "pm_snapshot.json"


def main() -> int:
    """Main entrypoint."""
    parser = argparse.ArgumentParser(description="Export PM snapshot as JSON")
    parser.add_argument("--output", type=Path, help="Output JSON file path (default: share/pm_snapshot.json)")

    args = parser.parse_args()

    # Ensure output directory exists
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    try:
        from agentpm.status.snapshot import get_system_snapshot

        snapshot = get_system_snapshot(
            include_reality_check=True,
            include_ai_tracking=True,
            include_share_manifest=True,
            include_eval_insights=True,
            include_kb_registry=True,
            include_kb_doc_health=True,
            include_mcp_catalog=True,
            reality_check_mode="HINT",  # HINT mode for snapshot speed
            use_lm_for_explain=False,  # Skip LM for snapshot speed
        )

        output_path = args.output if args.output else OUT_FILE
        if not output_path.is_absolute():
            output_path = REPO / output_path

        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(
            json.dumps(snapshot, indent=2, default=str),
            encoding="utf-8",
        )
        print(f"✅ Exported PM snapshot to {output_path}")
        return 0
    except Exception as exc:
        print(f"ERROR: Failed to export PM snapshot: {exc}", file=sys.stderr)
        # Write error export
        error_data = {
            "schema": "pm_snapshot.v1",
            "error": f"Failed to generate snapshot: {exc!s}",
        }
        output_path = args.output if args.output else OUT_FILE
        if not output_path.is_absolute():
            output_path = REPO / output_path
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(
            json.dumps(error_data, indent=2, default=str),
            encoding="utf-8",
        )
        return 1


if __name__ == "__main__":
    sys.exit(main())
