name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
      - name: No Mocks Guard
        run: scripts/ci-no-mocks.sh
      - name: Lint
        run: make lint || true
      - name: Type Check
        run: make type || true
      - name: Unit Tests
        run: make test.unit || true
      - name: Integration Tests
        run: make test.int || true
      - name: Coverage
        run: make coverage.report || true
