#!/usr/bin/env python3
"""
OPS Script: Implement Schema-to-Docsite Automation (Enhancement A)
==================================================================
1. Installs `scripts/generate_schema_docs.py`.
2. Patches `scripts/governance_housekeeping.py` to run generation before updates.
"""

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
GEN_SCRIPT = REPO_ROOT / "scripts/generate_schema_docs.py"
GOV_SCRIPT = REPO_ROOT / "scripts/governance_housekeeping.py"

GEN_CONTENT = """#!/usr/bin/env python3
\"\"\"
Auto-generate documentation from JSON schemas.
\"\"\"
import json
import glob
from pathlib import Path

def main():
    print("Generating schema documentation...")
    schemas = glob.glob("docs/SSOT/*.schema.json") + glob.glob("schemas/*.schema.json")
    output_file = Path("docs/SSOT/auto_schema_output.md")
    
    with open(output_file, "w") as f:
        f.write("# Auto-Generated Schema Documentation\\n\\n")
        f.write("This file is auto-generated by `scripts/generate_schema_docs.py`. Do not edit manually.\\n\\n")
        f.write("| Schema File | Title | Description |\\n")
        f.write("|---|---|---|\\n")
        
        for schema_path in sorted(schemas):
            try:
                with open(schema_path) as sf:
                    data = json.load(sf)
                    title = data.get("title", Path(schema_path).name)
                    desc = data.get("description", "No description").split("\\n")[0]
                    f.write(f"| `{schema_path}` | {title} | {desc} |\\n")
            except Exception as e:
                print(f"Error reading {schema_path}: {e}")
                
    print(f"Generated {output_file}")

if __name__ == "__main__":
    main()
"""


def install_generator():
    print(f"Installing {GEN_SCRIPT}...")
    GEN_SCRIPT.write_text(GEN_CONTENT)
    GEN_SCRIPT.chmod(0o755)
    print("✓ Generator script installed")


def patch_governance_housekeeping():
    print(f"Patching {GOV_SCRIPT}...")
    content = GOV_SCRIPT.read_text()

    if "def generate_schema_docs():" in content:
        print("✓ governance_housekeeping.py already patched")
        return

    # Add function definition
    new_function = """
def generate_schema_docs():
    \"\"\"Generate schema documentation.\"\"\"
    return run_command(
        [sys.executable, "scripts/generate_schema_docs.py"],
        "Generating schema documentation",
    )
"""
    # Insert before update_governance_artifacts
    if "def update_governance_artifacts():" in content:
        content = content.replace(
            "def update_governance_artifacts():",
            new_function + "\n\ndef update_governance_artifacts():",
        )
    else:
        print("❌ Could not find update_governance_artifacts function to insert before")
        return

    # Update operations list
    # We want to insert it at the start of operations list
    if "operations = [" in content:
        content = content.replace(
            "operations = [",
            'operations = [\n        ("Generate schema documentation", generate_schema_docs),',
        )
    else:
        print("❌ Could not find operations list")
        return

    GOV_SCRIPT.write_text(content)
    print("✓ governance_housekeeping.py patched")


def main():
    install_generator()
    patch_governance_housekeeping()
    print("SUCCESS: Schema-to-Docsite Automation implemented")


if __name__ == "__main__":
    main()
