#!/usr/bin/env python
"""
generate_pm_bootstrap_state.py

Generate share/PM_BOOTSTRAP_STATE.json — a minimal index of critical SSOT docs
for new PM chats.

This script is **non-destructive**: it only writes a small JSON summary.
If a referenced file is missing, it logs a warning but still writes the file.
"""

import json
import os
from pathlib import Path
from datetime import datetime, timezone

ROOT = Path(__file__).resolve().parents[2]
SSOT = ROOT / "docs" / "SSOT"
SHARE = ROOT / "share"
OUT = SHARE / "PM_BOOTSTRAP_STATE.json"


def exists(rel_path: str) -> bool:
    return (ROOT / rel_path).exists()


def optional(path: str):
    return path if exists(path) else None


def main() -> int:
    branch = os.popen("git rev-parse --abbrev-ref HEAD").read().strip() or None
    ts = datetime.now(timezone.utc).isoformat()

    data = {
        "version": "2025-12-03",
        "generated_at_utc": ts,
        "branch": branch,
        "description": "Minimal PM bootstrap index for new chats. All paths are repo-relative.",
        "core_governance": {
            "pm_contract": optional("docs/SSOT/PM_CONTRACT.md"),
            "execution_contract": optional("docs/SSOT/EXECUTION_CONTRACT.md"),
            "cursor_behavior_patch": optional("docs/SSOT/CURSOR_BEHAVIORAL_PATCH.md"),
        },
        "gotchas": {
            "index": optional("docs/SSOT/GOTCHAS_INDEX.md"),
            "share_folder": optional("docs/SSOT/PM_SHARE_FOLDER_GOTCHAS.md"),
            "share_gate_status": optional("docs/SSOT/SHARE_FOLDER_GATE_STATUS_GAP.md"),
        },
        "projects": {
            "inventory": optional("docs/SSOT/PROJECTS_INVENTORY.md"),
        },
        "infra": {
            "housekeeping_gpu": optional("docs/SSOT/HOUSEKEEPING_GPU_ACCELERATION.md"),
            "housekeeping_perf": optional("docs/SSOT/HOUSEKEEPING_PERFORMANCE_OPTIMIZATION.md"),
            "postgres_review": optional("docs/SSOT/POSTGRES_OPTIMIZATION_REVIEW.md"),
            "dsn_governance": optional("docs/SSOT/GEMATRIA_DSN_GOVERNANCE.md"),
        },
        "phases": {
            "8": {
                "diagnostic": optional("docs/SSOT/PHASE8_PHASE10_DIAGNOSTIC.md"),
            },
            "10": {
                "wiring_self_assessment": optional("docs/SSOT/PHASE10_WIRING_SELF_ASSESSMENT.md"),
                "correlation_wiring_complete": optional("docs/SSOT/PHASE10_CORRELATION_WIRING_COMPLETE.md"),
            },
            "15": {
                "compass_structural_gap": optional("docs/SSOT/PHASE15_COMPASS_STRUCTURAL_GAP.md"),
                "status_correction": optional("docs/SSOT/PHASE15_STATUS_CORRECTION.md"),
                "wave3_step2_status": optional("docs/SSOT/PHASE15_WAVE3_STEP2_STATUS.md"),
            },
        },
        "kb": {
            "registry_course_correction": optional("docs/SSOT/KB_REGISTRY_ARCHITECTURAL_COURSE_CORRECTION.md"),
            "share_layout_phase15": optional("docs/SSOT/PM_SHARE_LAYOUT_PHASE15.md"),
        },
        "notes": [
            "This file is the only thing a new PM chat strictly needs to start.",
            "If a path is null, that doc does not exist in this branch.",
            "Generated by scripts/pm/generate_pm_bootstrap_state.py.",
        ],
    }

    # Drop keys with null values to keep the file small
    def prune(obj):
        if isinstance(obj, dict):
            return {k: prune(v) for k, v in obj.items() if v is not None}
        if isinstance(obj, list):
            return [prune(x) for x in obj]
        return obj

    pruned = prune(data)
    SHARE.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(pruned, indent=2, sort_keys=True), encoding="utf-8")
    print(f"[PM_BOOTSTRAP] Wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

