#!/usr/bin/env python3
"""
AI Documentation Helper for pmagent reality-check

Uses Granite (LM Studio) to generate orchestrator-facing notes about the reality-check system.
Handles LM-off gracefully (no crashes; just prints explanation).
"""

from __future__ import annotations

import sys
from datetime import datetime, UTC
from pathlib import Path

# Add project root to path
ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(ROOT))

from pmagent.adapters.lm_studio import lm_studio_chat  # noqa: E402


def read_reality_check_code() -> str:
    """Read the reality-check implementation code."""
    code_path = ROOT / "pmagent" / "reality" / "check.py"
    if code_path.exists():
        return code_path.read_text(encoding="utf-8")
    return ""


def read_reality_check_design() -> str:
    """Read the reality-check design document."""
    design_path = ROOT / "docs" / "SSOT" / "PMAGENT_REALITY_CHECK_DESIGN.md"
    if design_path.exists():
        return design_path.read_text(encoding="utf-8")
    return ""


def read_agents_md_section() -> str:
    """Read the reality-check section from AGENTS.md."""
    agents_path = ROOT / "AGENTS.md"
    if agents_path.exists():
        content = agents_path.read_text(encoding="utf-8")
        # Extract reality-check section (lines around "Reality Check Agent")
        lines = content.split("\n")
        start_idx = None
        end_idx = None
        for i, line in enumerate(lines):
            if "Reality Check Agent" in line or "reality-check" in line.lower():
                if start_idx is None:
                    start_idx = max(0, i - 5)  # Include some context before
            if start_idx is not None and i > start_idx + 50:
                # Stop after ~50 lines or at next major section
                if line.startswith("####") and "Reality Check" not in line:
                    end_idx = i
                    break
        if start_idx is not None:
            end_idx = end_idx or min(start_idx + 100, len(lines))
            return "\n".join(lines[start_idx:end_idx])
    return ""


def build_prompt() -> str:
    """Build the prompt for Granite."""
    code = read_reality_check_code()
    design = read_reality_check_design()
    agents_section = read_agents_md_section()

    prompt = f"""You are the Granite housekeeping AI for the Gemantria project.

I need you to summarize pmagent reality-check & bringup.live for the human Orchestrator in 2-3 short sections:

(1) "What this check actually does today"
(2) "How to use it in practice"
(3) "Open questions or TODOs the PM should decide"

Output as Markdown, no code, no YAML.

Here is the implementation code:

```python
{code[:3000]}  # Truncated for brevity
```

Here is the design document:

```markdown
{design[:3000]}  # Truncated for brevity
```

Here is the AGENTS.md section:

```markdown
{agents_section[:2000]}  # Truncated for brevity
```

Please provide a concise, orchestrator-facing summary in Markdown format."""

    return prompt


def generate_ai_notes() -> tuple[str, bool]:
    """
    Generate AI notes using Granite (LM Studio).

    Returns:
        Tuple of (notes_content, lm_was_available)
    """
    prompt = build_prompt()

    # Call LM Studio adapter (handles lm_off gracefully)
    result = lm_studio_chat(
        messages=[
            {
                "role": "system",
                "content": "You are a technical documentation assistant for the Gemantria project. Provide clear, concise summaries for human orchestrators.",
            },
            {"role": "user", "content": prompt},
        ],
        temperature=0.2,
        max_tokens=1500,
        model_slot="local_agent",  # Use local_agent slot for Granite
    )

    if result.get("ok") and result.get("mode") == "lm_on":
        response = result.get("response", {})
        choices = response.get("choices", [])
        if choices:
            content = choices[0].get("message", {}).get("content", "")
            if content:
                return content, True

    # LM was not available
    return "", False


def write_ai_notes_file(content: str, lm_available: bool) -> Path:
    """
    Write AI notes to the SSOT directory.

    Args:
        content: The notes content (empty if LM was unavailable)
        lm_available: Whether LM was available

    Returns:
        Path to the written file
    """
    output_path = ROOT / "docs" / "SSOT" / "PMAGENT_REALITY_CHECK_AI_NOTES.md"
    output_path.parent.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now(UTC).isoformat()

    if not lm_available or not content:
        # Write a note that LM was offline
        note = f"""# pmagent reality-check — AI-Generated Notes

> **Status**: Granite offline; no fresh AI notes generated.
> **Last run**: {timestamp}
>
> This file is automatically generated by `pmagent docs reality-check-ai-notes`.
> When Granite (LM Studio) is available, it will generate orchestrator-facing notes
> summarizing the reality-check system.
>
> To generate fresh notes, ensure LM Studio is running and configured, then run:
> ```bash
> python -m pmagent docs reality-check-ai-notes
> ```
"""
    else:
        # Write the AI-generated content
        note = f"""# pmagent reality-check — AI-Generated Notes

> **Generated**: {timestamp}
> **Model**: Granite (via LM Studio)
>
> This file is automatically generated by `pmagent docs reality-check-ai-notes`.
> It provides orchestrator-facing notes about the reality-check system.

---

{content}
"""

    output_path.write_text(note, encoding="utf-8")
    return output_path


def main() -> int:
    """Main entry point for the AI docs helper."""
    try:
        content, lm_available = generate_ai_notes()
        output_path = write_ai_notes_file(content, lm_available)

        if lm_available:
            print(f"✓ AI notes generated: {output_path}", file=sys.stderr)
        else:
            print(f"⚠ Granite offline; placeholder written: {output_path}", file=sys.stderr)
            print("  (This is safe; the helper is advisory only.)", file=sys.stderr)

        return 0

    except Exception as e:
        print(f"ERROR: Failed to generate AI notes: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
