#!/bin/bash

# Figma Design Workflow Checker
# Uses MCP tools to analyze your current Figma design state

echo "🔍 Checking your Figma design workflow..."
echo "=========================================="
echo ""
echo "📋 WORKFLOW ANALYSIS STEPS:"
echo ""
echo "1️⃣  DOCUMENT OVERVIEW:"
echo "   Run in Cursor: get_document_info"
echo ""
echo "2️⃣  CURRENT SELECTION:"
echo "   Run in Cursor: get_selection"
echo ""
echo "3️⃣  TEXT CONTENT SCAN:"
echo "   Run in Cursor: scan_text_nodes"
echo ""
echo "4️⃣  COMPONENT LIBRARY:"
echo "   Run in Cursor: get_local_components"
echo ""
echo "5️⃣  PROTOTYPE FLOWS:"
echo "   Run in Cursor: get_reactions"
echo ""
echo "6️⃣  DESIGN ANALYSIS:"
echo "   Run in Cursor: read_my_design"
echo ""
echo "💡 TIPS:"
echo "- Start with get_document_info to see your file structure"
echo "- Use scan_text_nodes to find text that might need updates"
echo "- Check get_reactions for user flow connections"
echo "- Look at get_local_components for reusable elements"
echo ""
echo "🎯 COMMON WORKFLOWS TO ANALYZE:"
echo ""
echo "For Content Updates:"
echo "  → scan_text_nodes → set_multiple_text_contents"
echo ""
echo "For Design Systems:"
echo "  → get_local_components → create_component_instance"
echo ""
echo "For User Flows:"
echo "  → get_reactions → create_connections"
echo ""
echo "For New Features:"
echo "  → create_frame → create_text → set_fill_color"
echo ""
echo "🚀 Ready to analyze your design workflow!"
echo "   Run the MCP commands above in Cursor to get started."
