#!/usr/bin/env python3
"""
Auto-generate documentation from JSON schemas.
"""

import json
import glob
from pathlib import Path


def main():
    print("Generating schema documentation...")
    schemas = glob.glob("docs/SSOT/*.schema.json") + glob.glob("schemas/*.schema.json")
    output_file = Path("docs/SSOT/auto_schema_output.md")

    with open(output_file, "w") as f:
        f.write("# Auto-Generated Schema Documentation\n\n")
        f.write("This file is auto-generated by `scripts/generate_schema_docs.py`. Do not edit manually.\n\n")
        f.write("| Schema File | Title | Description |\n")
        f.write("|---|---|---|\n")

        for schema_path in sorted(schemas):
            try:
                with open(schema_path) as sf:
                    data = json.load(sf)
                    title = data.get("title", Path(schema_path).name)
                    desc = data.get("description", "No description").split("\n")[0]
                    f.write(f"| `{schema_path}` | {title} | {desc} |\n")
            except Exception as e:
                print(f"Error reading {schema_path}: {e}")

    print(f"Generated {output_file}")


if __name__ == "__main__":
    main()
