%% generated (HINT) 2025-11-10T20:22:27Z
gantt
  dateFormat  YYYY-MM-DD
  title Pipeline (30d)
  section ETL
  Ingest     :done, des1, 2025-11-04, 1d
  Normalize  :done, des2, 2025-11-05, 1d
  Enrich     :active, des3, 2025-11-06, 2d
  Persist    :         des4, 2025-11-08, 1d
